/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'haochen' at '3/19/15 8:32 PM' with Gradle 2.2.1
 *
 * @author haochen, @date 3/19/15 8:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
